# Generated by Django 2.2.3 on 2019-07-20 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_honor'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genres',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(max_length=13)),
                ('title', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('first_published', models.DateField(blank=True)),
                ('language', models.CharField(max_length=20)),
                ('book_cover', models.ImageField(upload_to='bookCovers/')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Genre')),
                ('written_by', models.ManyToManyField(to='authors.Author')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
