# Generated by Django 2.2.3 on 2019-07-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190720_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='<em>ISBN: 9780-0-143-02857-4</em>', max_length=17),
        ),
    ]
