# Generated by Django 2.2.3 on 2019-07-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
