# Generated by Django 2.2.3 on 2019-07-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_honor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
    ]
