# Generated by Django 2.2.3 on 2019-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20190720_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='honor',
            field=models.CharField(choices=[('Miss.', 'miss'), ('Mr.', 'mr'), ('Mrs.', 'mrs')], default='Mr.', max_length=4),
        ),
    ]
